from __future__ import annotations

import re
from typing import Any

# ATS suffixes used when the same firm was entered twice with another board.
_ATS_SUFFIX = re.compile(
    r"\s+(Workable|Recruitee|Greenhouse|Ashby|Lever|SmartRecruiters|"
    r"Personio|Breezy|Pinpoint|BambooHR|Eightfold|iCIMS|Join|Rippling|"
    r"JazzHR|Freshteam|Softgarden|Teamtailor|Careers|Jobs)$",
    re.I,
)

ALIASES = {
    "Adobe Romania": "Adobe",
    "Adobe University": "Adobe",
    "Adobe BambooHR": "Adobe",
    "UiPath Bucharest": "UiPath",
    "UiPath Greenhouse": "UiPath",
    "UiPath Breezy": "UiPath",
    "Bitdefender Careers": "Bitdefender",
    "Bitdefender Recruitee": "Bitdefender",
    "Bitdefender Breezy": "Bitdefender",
    "eMAG Jobs": "eMAG",
    "eMAG Recruitee": "eMAG",
    "eMAG Breezy": "eMAG",
    "ING Tech Romania": "ING",
    "ING Hubs Romania": "ING",
    "ING Recruitee": "ING",
    "ING Breezy": "ING",
    "Nokia Careers": "Nokia",
    "Nokia Workable": "Nokia",
    "Ericsson Careers": "Ericsson",
    "Ericsson Workable": "Ericsson",
    "Siemens Jobs": "Siemens",
    "Siemens Workable": "Siemens",
    "P&G SmartRecruiters": "Procter & Gamble",
    "HP SmartRecruiters": "HP",
    "Oracle SmartRecruiters": "Oracle",
    "Lenovo SmartRecruiters": "Lenovo",
    "Amazon iCIMS": "Amazon",
    "IBM iCIMS": "IBM",
    "Cisco Eightfold": "Cisco",
    "NVIDIA Eightfold": "NVIDIA",
    "Jane Street Europe": "Jane Street",
    "Jane Street Ashby": "Jane Street",
    "Jane Street Pinpoint": "Jane Street",
    "Cloudflare Europe": "Cloudflare",
    "N26 Personio": "N26",
    "Wolt Personio": "Wolt",
    "Trade Republic Personio": "Trade Republic",
    "Wise Ashby": "Wise",
    "Revolut Ashby": "Revolut",
    "Optiver Amsterdam": "Optiver",
    "Optiver Lever": "Optiver",
    "Optiver Pinpoint": "Optiver",
    "Flow Traders Jobs": "Flow Traders",
    "Jump Trading Europe": "Jump Trading",
    "Jump Lever": "Jump Trading",
    "Jump Crypto": "Jump Trading",
    "DRW Europe": "DRW",
    "Hudson River Trading Europe": "Hudson River Trading",
    "HRT Ashby": "Hudson River Trading",
    "Citadel Ashby": "Citadel",
    "Citadel Pinpoint": "Citadel",
    "Citadel Securities": "Citadel",
    "Two Sigma Ashby": "Two Sigma",
    "XTX Ashby": "XTX Markets",
    "G-Research Ashby": "G-Research",
    "G-Research Pinpoint": "G-Research",
    "IMC Lever": "IMC Trading",
    "IMC Pinpoint": "IMC Trading",
    "SIG Lever": "Susquehanna",
    "Qube RT": "Qube Research & Technologies",
    "Continental SmartRecruiters": "Continental",
    "Bosch Workable": "Bosch",
    "Garmin SmartRecruiters": "Garmin",
    "Ubisoft SmartRecruiters": "Ubisoft",
    "Orange Workable": "Orange Romania",
    "Vodafone Workable": "Vodafone",
    "Digi Workable": "Digi RCS RDS",
    "Societe Generale EBS": "Societe Generale GSC",
    "Societe Generale GSC": "Societe Generale",
    "DB Global Technology": "Deutsche Bank",
    "DB Systel": "Deutsche Bank",
    "Allianz Technology": "Allianz",
    "Allianz-Tiriac": "Allianz",
    "Druid": "Druid AI",
    "Druid Recruitee": "Druid AI",
    "FintechOS Jobs": "FintechOS",
    "FintechOS Recruitee": "FintechOS",
    "FlowX Workable": "FlowX.AI",
    "Superbet Greenhouse": "Superbet",
    "Superbet Workable": "Superbet",
    "Amber Recruitee": "Amber Studio",
    "Gameloft Workable": "Gameloft",
    "Cognizant Softvision": "Cognizant",
    "Softvision": "Cognizant",
    "Altran": "Capgemini",
    "Sogeti": "Capgemini",
    "Capgemini Engineering": "Capgemini",
    "Atos": "Eviden",
    "Accesa IT": "Accesa",
    "AROBS Transilvania Software": "AROBS",
    "AROBS Group": "AROBS",
    "Alpha Bank Romania": "Alpha Bank",
    "Garanti BBVA Romania": "Garanti BBVA",
    "First Bank Romania": "First Bank",
    "CEC Bank Romania": "CEC Bank",
    "Netopia Payments": "Netopia",
    "2Performant Network": "2Performant",
    "Boston Consulting Group": "BCG",
    "Bain & Company": "Bain",
    "J.P. Morgan Chase": "J.P. Morgan",
    "JPMorgan": "J.P. Morgan",
    "Goldman Sachs Group": "Goldman Sachs",
    "Bank of America Merrill Lynch": "Bank of America",
    "Citigroup": "Citi",
    "UBS Group": "UBS",
    "HSBC Holdings": "HSBC",
    "BNP Paribas CIB": "BNP Paribas",
    "Lloyds Banking Group": "Lloyds",
    "NatWest Group": "NatWest",
    "Fidelity International": "Fidelity",
    "The Bank of New York Mellon": "BNY Mellon",
    "DXC Technology": "DXC",
    "Harman International": "HARMAN",
    "Magna International": "Magna",
    "ZF Friedrichshafen": "ZF",
    "Volvo Cars": "Volvo",
    "Jaguar Land Rover": "Jaguar Land Rover",
    "BMW Group": "BMW",
    "Volkswagen Group": "Volkswagen",
    "TTTech": "TTTech Auto",
    "Vector": "Vector Informatik",
    "EngineersGate": "Engineers Gate",
    "PDT": "PDT Partners",
    "Exodus Point": "ExodusPoint",
    "AQR Capital": "AQR",
    "Box Inc": "Box",
    "Epic": "Epic Games",
    "Riot": "Riot Games",
}

OFFICIAL_CAREERS: dict[str, list[str]] = {
    "Google": ["https://www.google.com/about/careers/applications/jobs/results/"],
    "Amazon": ["https://www.amazon.jobs/"],
    "Microsoft": ["https://jobs.careers.microsoft.com/"],
    "Meta": ["https://www.metacareers.com/"],
    "Apple": ["https://jobs.apple.com/"],
    "Adobe": ["https://careers.adobe.com/", "https://adobe.wd5.myworkdayjobs.com/external_experienced"],
    "IBM": ["https://www.ibm.com/careers"],
    "SAP": ["https://jobs.sap.com/"],
    "Oracle": ["https://careers.oracle.com/"],
    "NVIDIA": ["https://www.nvidia.com/en-us/about-nvidia/careers/"],
    "Intel": ["https://jobs.intel.com/"],
    "Cisco": ["https://jobs.cisco.com/"],
    "Dell": ["https://jobs.dell.com/"],
    "Salesforce": ["https://careers.salesforce.com/"],
    "Uber": ["https://www.uber.com/careers/"],
    "Airbnb": ["https://careers.airbnb.com/"],
    "Stripe": ["https://stripe.com/jobs"],
    "Databricks": ["https://www.databricks.com/company/careers"],
    "Cloudflare": ["https://www.cloudflare.com/careers/"],
    "MongoDB": ["https://www.mongodb.com/careers"],
    "GitLab": ["https://about.gitlab.com/jobs/"],
    "Elastic": ["https://www.elastic.co/careers"],
    "Twilio": ["https://www.twilio.com/company/jobs"],
    "Okta": ["https://www.okta.com/company/careers/"],
    "Figma": ["https://www.figma.com/careers/"],
    "SpaceX": ["https://www.spacex.com/careers"],
    "Scale AI": ["https://scale.com/careers"],
    "Palantir": ["https://www.palantir.com/careers/"],
    "OpenAI": ["https://openai.com/careers"],
    "Anthropic": ["https://www.anthropic.com/careers"],
    "Notion": ["https://www.notion.com/careers"],
    "Snowflake": ["https://careers.snowflake.com/"],
    "Atlassian": ["https://www.atlassian.com/company/careers"],
    "Shopify": ["https://www.shopify.com/careers"],
    "Spotify": ["https://www.lifeatspotify.com/"],
    "Booking.com": ["https://jobs.booking.com/"],
    "Netflix": ["https://jobs.netflix.com/"],
    "CrowdStrike": ["https://www.crowdstrike.com/careers/"],
    "Jane Street": ["https://www.janestreet.com/join-jane-street/"],
    "Jump Trading": ["https://www.jumptrading.com/careers/"],
    "Optiver": ["https://optiver.com/working-at-optiver/career-opportunities/"],
    "IMC Trading": ["https://www.imc.com/us/careers"],
    "Flow Traders": ["https://www.flowtraders.com/careers"],
    "WorldQuant": ["https://www.worldquant.com/career-listing/"],
    "Akuna Capital": ["https://akunacapital.com/careers"],
    "Point72": ["https://careers.point72.com/"],
    "Citadel": ["https://www.citadel.com/careers/", "https://www.citadelsecurities.com/careers/"],
    "Two Sigma": ["https://careers.twosigma.com/"],
    "Hudson River Trading": ["https://www.hudsonrivertrading.com/careers/"],
    "D. E. Shaw": ["https://www.deshaw.com/careers"],
    "DRW": ["https://drw.com/careers"],
    "Tower Research": ["https://www.tower-research.com/positions"],
    "G-Research": ["https://www.gresearch.com/join-us/"],
    "XTX Markets": ["https://www.xtxmarkets.com/careers/"],
    "Virtu Financial": ["https://www.virtu.com/careers/"],
    "Susquehanna": ["https://careers.sig.com/"],
    "Five Rings": ["https://fiverings.com/careers/"],
    "Old Mission Capital": ["https://www.oldmissioncapital.com/careers/"],
    "QuantCo": ["https://quantco.com/careers/"],
    "ING": ["https://www.ing.jobs/", "https://www.ing.ro/ing-in-romania/cariere"],
    "Societe Generale": ["https://careers.societegenerale.com/"],
    "LSEG": ["https://www.lseg.com/en/careers"],
    "Bloomberg": ["https://www.bloomberg.com/company/careers/"],
    "Revolut": ["https://www.revolut.com/careers/"],
    "Wise": ["https://wise.jobs/"],
    "Superbet": ["https://superbet.ro/cariere"],
    "Flutter": ["https://careers.flutter.com/"],
    "Visa": ["https://usa.visa.com/careers.html"],
    "Mastercard": ["https://careers.mastercard.com/"],
    "PayPal": ["https://careers.pypl.com/"],
    "Adyen": ["https://careers.adyen.com/"],
    "N26": ["https://n26.com/en-eu/careers"],
    "Trade Republic": ["https://traderepublic.com/careers"],
    "Banca Transilvania": ["https://www.bancatransilvania.ro/cariere"],
    "Raiffeisen Bank": ["https://www.raiffeisen.ro/ro/despre-noi/cariere.html"],
    "BRD Groupe Societe Generale": ["https://www.brd.ro/cariere"],
    "UniCredit": ["https://www.unicredit.ro/ro/institutional/Cariere.html"],
    "Allianz": ["https://careers.allianz.com/", "https://www.allianztiriac.ro/cariere"],
    "Deutsche Bank": ["https://careers.db.com/"],
    "UiPath": ["https://www.uipath.com/company/careers"],
    "Bitdefender": ["https://www.bitdefender.com/careers"],
    "eMAG": ["https://cariere.emag.ro/"],
    "Druid AI": ["https://www.druidai.com/careers"],
    "FintechOS": ["https://www.fintechos.com/careers/"],
    "FlowX.AI": ["https://www.flowx.ai/careers"],
    "TypingDNA": ["https://www.typingdna.com/careers"],
    "Caphyon": ["https://www.caphyon.com/careers"],
    "Zitec": ["https://www.zitec.com/careers"],
    "Evozon": ["https://www.evozon.com/careers/"],
    "Softelligence": ["https://www.softelligence.net/careers/"],
    "Tapptitude": ["https://tapptitude.com/careers/"],
    "Qualitance": ["https://www.qualitance.com/careers/"],
    "Bolt": ["https://bolt.eu/en/careers/"],
    "Glovo": ["https://jobs.glovoapp.com/"],
    "Wolt": ["https://careers.wolt.com/"],
    "Canva": ["https://www.canva.com/careers/"],
    "Miro": ["https://miro.com/careers/"],
    "Ubisoft": ["https://www.ubisoft.com/en-us/company/careers"],
    "Gameloft": ["https://www.gameloft.com/corporate/jobs"],
    "Electronic Arts": ["https://www.ea.com/careers"],
    "King": ["https://careers.king.com/"],
    "Bosch": ["https://www.bosch.com/careers/", "https://www.bosch.ro/cariera/"],
    "Continental": ["https://career.continental.com/", "https://www.continental.com/en/career/"],
    "Siemens": ["https://jobs.siemens.com/"],
    "Garmin": ["https://careers.garmin.com/"],
    "Nokia": ["https://www.nokia.com/careers/"],
    "Ericsson": ["https://www.ericsson.com/en/careers"],
    "Thales": ["https://careers.thalesgroup.com/"],
    "Honeywell": ["https://careers.honeywell.com/"],
    "Infineon": ["https://www.infineon.com/cms/en/careers/"],
    "NXP": ["https://www.nxp.com/company/about-nxp/careers:CAREERS", "https://nxp.wd3.myworkdayjobs.com/careers"],
    "Analog Devices": ["https://www.analog.com/en/careers.html"],
    "Emerson": ["https://www.emerson.com/en-us/careers"],
    "SLB": ["https://careers.slb.com/"],
    "Keysight": ["https://jobs.keysight.com/"],
    "Microchip": ["https://careers.microchip.com/"],
    "Airbus": ["https://www.airbus.com/en/careers"],
    "AUMOVIO": ["https://www.aumovio.com/en/career"],
    "Orange Romania": ["https://www.orange.ro/despre-orange/cariere/"],
    "Vodafone": ["https://www.vodafone.ro/cariere"],
    "Digi RCS RDS": ["https://www.digi.ro/cariere"],
    "Telekom Romania": ["https://www.telekom.ro/despre-noi/cariere/"],
    "Huawei": ["https://career.huawei.com/"],
    "Endava": ["https://www.endava.com/careers"],
    "Cognizant": ["https://careers.cognizant.com/"],
    "Accenture": ["https://www.accenture.com/careers"],
    "NTT DATA": ["https://careers.nttdata.com/"],
    "Luxoft": ["https://career.luxoft.com/"],
    "EPAM": ["https://www.epam.com/careers"],
    "Globant": ["https://www.globant.com/careers"],
    "Capgemini": ["https://www.capgemini.com/careers/"],
    "Wipro": ["https://careers.wipro.com/"],
    "Infosys": ["https://www.infosys.com/careers/"],
    "TCS": ["https://www.tcs.com/careers"],
    "Fortech": ["https://www.fortech.ro/careers/"],
    "Yonder": ["https://www.yonder.ro/careers/"],
    "Tremend": ["https://www.tremend.com/careers/"],
    "Cegeka": ["https://www.cegeka.com/en/careers"],
    "PitechPlus": ["https://pitechplus.com/careers/"],
    "Deloitte": ["https://www.deloitte.com/ro/en/careers.html"],
    "PwC": ["https://www.pwc.com/ro/en/careers.html"],
    "EY": ["https://careers.ey.com/"],
    "KPMG": ["https://kpmg.com/ro/en/home/careers.html"],
    "Lidl": ["https://cariere.lidl.ro/"],
    "Kaufland": ["https://cariere.kaufland.ro/"],
    "Autodesk": ["https://www.autodesk.com/careers"],
    "ServiceNow": ["https://careers.servicenow.com/"],
    "Red Hat": ["https://www.redhat.com/en/jobs"],
    "GitHub": ["https://www.github.careers/"],
    "LinkedIn": ["https://careers.linkedin.com/"],
    "DeepMind": ["https://deepmind.google/careers/"],
    "Tesla": ["https://www.tesla.com/careers"],
    "HP": ["https://jobs.hp.com/"],
    "Qualcomm": ["https://careers.qualcomm.com/"],
    "Broadcom": ["https://www.broadcom.com/company/careers"],
    "STMicroelectronics": ["https://www.st.com/content/st_com/en/about/careers.html"],
    "ASML": ["https://www.asml.com/en/careers"],
    "Procter & Gamble": ["https://www.pgcareers.com/"],
    "Western Union": ["https://careers.westernunion.com/"],
    "Lenovo": ["https://jobs.lenovo.com/"],
    "ARM": ["https://careers.arm.com/"],
    "Renesas": ["https://www.renesas.com/us/en/about/careers"],
    "Marvell": ["https://www.marvell.com/company/careers.html"],
    "Micron": ["https://www.micron.com/careers"],
    "Ford Romania": ["https://corporate.ford.com/careers.html"],
    "Mercedes-Benz": ["https://group.mercedes-benz.com/careers/"],
    "Renault": ["https://www.renaultgroup.com/en/our-group/careers/"],
    "ABB": ["https://careers.abb/"],
    "Schneider Electric": ["https://www.se.com/ww/en/about-us/careers/"],
    "Eaton": ["https://www.eaton.com/us/en-us/company/careers.html"],
    "OMV Petrom": ["https://www.omvpetrom.com/ro/cariere"],
    "BCR": ["https://www.bcr.ro/ro/cariere"],
    "OTP Bank": ["https://www.otpbank.ro/ro/despre-noi/cariere"],
    "Datadog": ["https://careers.datadoghq.com/"],
    "Discord": ["https://discord.com/careers"],
    "Linear": ["https://linear.app/careers"],
    "Vercel": ["https://vercel.com/careers"],
    "Perplexity": ["https://www.perplexity.ai/careers"],
    "Rippling": ["https://www.rippling.com/careers"],
    "Ramp": ["https://ramp.com/careers"],
    "Deel": ["https://www.deel.com/careers"],
    "Personio": ["https://www.personio.com/about-personio/careers/"],
    "Celonis": ["https://www.celonis.com/careers/"],
    "Klarna": ["https://www.klarna.com/careers/"],
    "SumUp": ["https://www.sumup.com/careers/"],
    "Monzo": ["https://monzo.com/careers/"],
    "Starling Bank": ["https://www.starlingbank.com/careers/"],
    "Marshall Wace": ["https://www.mwam.com/join-us/"],
    "Man Group": ["https://www.man.com/careers"],
    "Squarepoint": ["https://www.squarepoint-capital.com/careers"],
    "AMIQ": ["https://www.amiq.com/careers/"],
    "Veridion": ["https://veridion.com/careers"],
    "FotoNation": ["https://www.xperi.com/careers/"],
    "FAN Courier": ["https://www.fancourier.ro/cariere/"],
    "AquaSoft": ["https://www.aquasoft.ro/careers"],
    "Arcanna.ai": ["https://www.arcanna.ai/careers"],
    "faur.ai": ["https://faur.ai/careers"],
    "3DAPI": ["https://3dapi.com/careers"],
    "Smartheads": ["https://smartheads.ro/careers"],
    "Schaeffler": ["https://www.schaeffler.com/en/career/"],
    "Forvia": ["https://www.forvia.com/en/talent"],
    "Valeo": ["https://www.valeo.com/en/join-us/"],
    "Autoliv": ["https://www.autoliv.com/career"],
    "Porsche Engineering": ["https://www.porscheengineering.com/peg/en/career/"],
    "Alstom": ["https://www.alstom.com/careers"],
    "Michelin": ["https://www.michelin.com/en/careers"],
    "GE Vernova": ["https://careers.gevernova.com/"],
    "RTX": ["https://careers.rtx.com/"],
    "HCLTech": ["https://www.hcltech.com/careers"],
    "Genpact": ["https://www.genpact.com/careers"],
    "Veeam": ["https://careers.veeam.com/"],
    "Thoughtworks": ["https://www.thoughtworks.com/careers"],
    "HashiCorp": ["https://www.hashicorp.com/careers"],
    "Anduril": ["https://www.anduril.com/careers/"],
    "Renaissance Technologies": ["https://www.rentec.com/Careers.action"],
    "Millennium": ["https://www.mlp.com/careers/"],
    "Wintermute": ["https://www.wintermute.com/careers"],
    "Maven Securities": ["https://www.mavensecurities.com/careers"],
    "Qube Research & Technologies": ["https://www.qube-rt.com/careers/"],
    "Fitbit": ["https://www.fitbit.com/global/us/careers"],
    "Playtika": ["https://www.playtika.com/careers/"],
    "Playtech": ["https://www.playtech.com/careers/"],
    "Kindred": ["https://www.kindredgroup.com/careers/"],
    "Kaizen Gaming": ["https://kaizengaming.com/careers/"],
    "Cegedim": ["https://www.cegedim.com/careers"],
    "IQVIA": ["https://jobs.iqvia.com/"],
    "PayU": ["https://corporate.payu.com/careers/"],
    "3Pillar Global": ["https://www.3pillarglobal.com/careers/"],
    "Mindera": ["https://mindera.com/careers/"],
    "Ness Digital": ["https://www.ness.com/careers/"],
    "Pentalog": ["https://www.pentalog.com/careers/"],
    "SoftServe": ["https://career.softserveinc.com/"],
    "Eviden": ["https://eviden.com/careers/"],
    "Frequentis": ["https://www.frequentis.com/career"],
    "Rohde Schwarz": ["https://www.rohde-schwarz.com/career"],
    "Phoenix Contact": ["https://www.phoenixcontact.com/en/career"],
    "Groupama": ["https://www.groupama.ro/cariere"],
    "NN Romania": ["https://www.nn.ro/cariere"],
    "Generali": ["https://www.generali.ro/cariere"],
    "Salt Bank": ["https://www.salt.ro/cariere"],
    "Libra Bank": ["https://www.librabank.ro/Cariere"],
    "METRO.digital": ["https://digital.metro.global/career/"],
    "Penny Romania": ["https://www.penny.ro/cariere"],
    "TotalSoft": ["https://www.totalsoft.ro/careers/"],
    "Senior Software": ["https://www.seniorsoftware.ro/careers/"],
    "ISDC": ["https://www.isdc.eu/careers/"],
    "Rinf.tech": ["https://www.rinf.tech/careers/"],
    "iQuest": ["https://www.iquestgroup.com/careers/"],
    "Roweb": ["https://www.roweb.ro/careers/"],
    "Softbinator": ["https://www.softbinator.com/careers"],
    "VTEX": ["https://careers.vtex.com/"],
    "Crossover": ["https://www.crossover.com/jobs"],
    "Delivery Hero": ["https://careers.deliveryhero.com/"],
    "GetYourGuide": ["https://www.getyourguide.com/careers/"],
    "Bitpanda": ["https://www.bitpanda.com/en/career"],
    "Showpad": ["https://www.showpad.com/careers/"],
    "Nexthink": ["https://www.nexthink.com/careers"],
    "Cresta": ["https://cresta.com/careers"],
    "Remote.com": ["https://remote.com/careers"],
    "onsemi": ["https://www.onsemi.com/careers"],
    "Applied Materials": ["https://www.appliedmaterials.com/us/en/careers.html"],
    "Lam Research": ["https://careers.lamresearch.com/"],
    "KLA": ["https://www.kla.com/careers"],
    "Draexlmaier": ["https://www.draexlmaier.com/career/"],
    "Preh": ["https://www.preh.com/en/career"],
    "Huf": ["https://www.huf-group.com/en/career"],
    "Leoni": ["https://www.leoni.com/en/career/"],
    "Yazaki": ["https://www.yazaki-europe.com/career"],
    "Bertrandt": ["https://www.bertrandt.com/en/career/"],
    "AKKA": ["https://www.akkamc.com/careers"],
    "Segula": ["https://www.segulatechnologies.com/en/join-us/"],
    "MHP": ["https://www.mhp.com/en/career"],
    "888 Holdings": ["https://www.888holdingsplc.com/careers/"],
    "Betano": ["https://www.betano.ro/"],
    "MaxBet": ["https://www.maxbet.ro/"],
    "MultiversX": ["https://multiversx.com/careers"],
    "SeedBlink": ["https://seedblink.com/careers"],
    "SmartDreamers": ["https://smartdreamers.com/careers"],
    "123FormBuilder": ["https://www.123formbuilder.com/careers/"],
    "Vector Watch": ["https://www.vectorwatch.com/"],
    "Thinslices": ["https://www.thinslices.com/careers"],
    "Azimut": ["https://www.azimut-advantage.com/careers"],
    "Modex": ["https://modex.tech/careers/"],
    "Gieom": ["https://www.gieom.com/careers"],
    "Stillfront": ["https://stillfront.com/en/career/"],
    "Soft2Bet": ["https://soft2bet.com/careers/"],
    "Evolution": ["https://www.evolution.com/careers/"],
    "Amber Studio": ["https://amberstudio.com/careers/"],
    "Winton": ["https://www.winton.com/careers"],
    "Capula": ["https://www.capulaglobal.com/careers/"],
    "Balyasny": ["https://www.bamfunds.com/careers"],
    "Cubist": ["https://www.cubistsystematic.com/"],
    "Aquatic Capital": ["https://aquaticcapital.com/careers"],
    "Radix Trading": ["https://radixtrading.co/"],
    "AXQ Capital": ["https://www.axqcapital.com/"],
    "Belvedere Trading": ["https://www.belvederetrading.com/careers/"],
    "TransMarket Group": ["https://www.transmarketgroup.com/careers"],
    "Chicago Trading Company": ["https://www.chicagotrading.com/careers"],
    "Peak6": ["https://peak6.com/careers/"],
    "Wolverine Trading": ["https://www.wolve.com/careers"],
    "Nethermind": ["https://www.nethermind.io/careers"],
    "Accesa": ["https://www.accesa.eu/careers", "https://careers.smartrecruiters.com/Accesa"],
    "AROBS": ["https://arobs.com/careers-at-arobs/", "https://apply.workable.com/arobs/"],
    "Nagarro": ["https://www.nagarro.com/en/careers", "https://apply.workable.com/nagarro/"],
    "Alten": ["https://www.alten.com/careers/", "https://careers.smartrecruiters.com/Alten"],
    "SelfPay": ["https://selfpay.ro/cariere/", "https://careers.smartrecruiters.com/SelfPay"],
    "Oblio": ["https://www.oblio.eu/cariere", "https://apply.workable.com/oblio/"],
    "Alpha Bank": ["https://www.alphabank.ro/cariere", "https://apply.workable.com/alphabank/"],
    "Kyndryl": ["https://www.kyndryl.com/careers", "https://apply.workable.com/kyndryl/"],
    "DXC": ["https://careers.dxc.com/", "https://apply.workable.com/dxc/"],
    "CGI": ["https://www.cgi.com/en/careers", "https://apply.workable.com/cgi/"],
    "Unisys": ["https://www.unisys.com/careers/", "https://apply.workable.com/unisys/"],
    "Fujitsu": ["https://www.fujitsu.com/global/about/careers/", "https://apply.workable.com/fujitsu/"],
    "Hitachi": ["https://careers.hitachi.com/", "https://apply.workable.com/hitachi/"],
    "Sony": ["https://www.sony.com/en/careers/", "https://apply.workable.com/sony/"],
    "Samsung": ["https://www.samsung.com/ro/about-us/careers/"],
    "SUSE": ["https://www.suse.com/company/careers/", "https://apply.workable.com/suse/"],
    "HARMAN": ["https://www.harman.com/careers", "https://apply.workable.com/harman/"],
    "Magna": ["https://www.magna.com/careers", "https://apply.workable.com/magna/"],
    "Aptiv": ["https://www.aptiv.com/en/careers", "https://apply.workable.com/aptiv/"],
    "Lear": ["https://www.lear.com/careers", "https://apply.workable.com/lear/"],
    "Visteon": ["https://www.visteon.com/careers/", "https://apply.workable.com/visteon/"],
    "MAHLE": ["https://www.mahle.com/en/careers/", "https://apply.workable.com/mahle/"],
    "Marelli": ["https://www.marelli.com/careers/", "https://apply.workable.com/marelli/"],
    "AVL": ["https://www.avl.com/en/career", "https://apply.workable.com/avl/"],
    "Vector Informatik": ["https://www.vector.com/int/en/careers/", "https://apply.workable.com/vector/"],
    "Roland Berger": ["https://www.rolandberger.com/en/Join/"],
    "Oliver Wyman": ["https://www.oliverwyman.com/careers.html"],
    "BCG": ["https://careers.bcg.com/"],
    "Bain": ["https://www.bain.com/careers/"],
    "McKinsey": ["https://www.mckinsey.com/careers"],
    "Kearney": ["https://www.kearney.com/careers"],
    "Strategy&": ["https://www.strategyand.pwc.com/careers"],
    "BearingPoint": ["https://www.bearingpoint.com/en/careers/"],
    "Canonical": ["https://canonical.com/careers"],
    "Confluent": ["https://www.confluent.io/careers/"],
    "Redis": ["https://redis.io/careers/"],
    "AQR": ["https://www.aqr.com/careers"],
    "Schonfeld": ["https://www.schonfeld.com/careers/"],
    "ExodusPoint": ["https://www.exoduspoint.com/careers/"],
    "Engineers Gate": ["https://www.eglp.com/careers"],
    "PDT Partners": ["https://www.pdtpartners.com/careers"],
    "Asana": ["https://asana.com/jobs"],
    "Dropbox": ["https://jobs.dropbox.com/"],
    "Box": ["https://www.box.com/careers"],
    "Pinterest": ["https://www.pinterestcareers.com/"],
    "Coinbase": ["https://www.coinbase.com/careers"],
    "Binance": ["https://www.binance.com/en/careers"],
    "OKX": ["https://www.okx.com/careers"],
    "Reddit": ["https://www.redditinc.com/careers"],
    "Roblox": ["https://careers.roblox.com/"],
    "Epic Games": ["https://www.epicgames.com/site/en-US/careers"],
    "Riot Games": ["https://www.riotgames.com/en/work-with-us"],
    "Twitch": ["https://www.twitch.tv/jobs"],
    "Zendesk": ["https://www.zendesk.com/jobs/"],
    "Unity": ["https://careers.unity.com/"],
    "Barclays": ["https://barclays.wd3.myworkdayjobs.com/External_Career_Site_Barclays", "https://home.barclays/careers/"],
    "Citi": ["https://citi.wd5.myworkdayjobs.com/2", "https://careers.citigroup.com/"],
    "Goldman Sachs": ["https://www.goldmansachs.com/careers/"],
    "J.P. Morgan": ["https://careers.jpmorgan.com/"],
    "Morgan Stanley": ["https://www.morganstanley.com/careers"],
    "Bank of America": ["https://careers.bankofamerica.com/"],
    "HSBC": ["https://www.hsbc.com/careers"],
    "UBS": ["https://www.ubs.com/global/en/careers.html"],
    "BlackRock": ["https://careers.blackrock.com/"],
    "BNP Paribas": ["https://group.bnpparibas/en/careers"],
    "Macquarie": ["https://www.macquarie.com/careers.html"],
    "Nomura": ["https://www.nomura.com/careers/"],
    "Standard Chartered": ["https://www.sc.com/en/careers/"],
    "NatWest": ["https://jobs.natwestgroup.com/"],
    "Lloyds": ["https://www.lloydsbankinggroup.com/careers.html"],
    "Schroders": ["https://www.schroders.com/en/careers/"],
    "Fidelity": ["https://jobs.fidelity.com/"],
    "State Street": ["https://careers.statestreet.com/"],
    "BNY Mellon": ["https://www.bnymellon.com/us/en/careers.html"],
    "Aviva": ["https://careers.aviva.com/"],
    "Storytel": ["https://www.storytel.com/careers"],
    "About You": ["https://corporate.aboutyou.de/en/career"],
    "Westwing": ["https://www.westwing.com/careers/"],
    "SmartBill": ["https://www.smartbill.ro/cariere"],
    "2Performant": ["https://2performant.com/careers/"],
    "Netopia": ["https://netopia-payments.com/cariere/"],
    "Sameday": ["https://www.sameday.ro/cariere"],
    "Cargus": ["https://www.cargus.ro/cariere/"],
    "Syneto": ["https://syneto.eu/careers/"],
    "Codezilla": ["https://codezilla.ro/careers"],
    "Finqware": ["https://finqware.com/careers"],
    "First Bank": ["https://www.firstbank.ro/cariere"],
    "CEC Bank": ["https://www.cec.ro/cariere"],
    "Garanti BBVA": ["https://www.garantibbva.ro/ro/cariere"],
    "TBI Bank": ["https://tbibank.ro/cariere"],
    "Intesa Sanpaolo": ["https://www.intesasanpaolobank.ro/cariere"],
    "Edenred": ["https://www.edenred.ro/ro/cariere"],
    "Pluxee": ["https://www.pluxee.ro/cariere"],
    "PPC Romania": ["https://www.ppcenergy.ro/cariere"],
    "E.ON": ["https://www.eon.ro/cariere"],
    "Engie": ["https://www.engie.ro/cariere"],
    "BMW": ["https://www.bmwgroup.jobs/"],
    "Volkswagen": ["https://www.volkswagen-group.com/en/careers"],
    "Stellantis": ["https://careers.stellantis.com/"],
    "Volvo": ["https://www.volvogroup.com/en/careers.html"],
    "Jaguar Land Rover": ["https://www.jaguarlandrovercareers.com/"],
    "Scania": ["https://www.scania.com/group/en/home/career.html"],
    "Iveco": ["https://www.ivecogroup.com/careers"],
    "Brose": ["https://www.brose.com/de-en/career/"],
    "Kostal": ["https://www.kostal.com/en-gb/career"],
    "SKF": ["https://www.skf.com/group/careers"],
    "Cummins": ["https://www.cummins.com/careers"],
    "Caterpillar": ["https://careers.caterpillar.com/"],
    "John Deere": ["https://www.deere.com/en/our-company/john-deere-careers/"],
    "Porsche": ["https://www.porsche.com/international/aboutporsche/jobs/"],
    "Audi": ["https://www.audi.com/en/careers.html"],
    "Toyota": ["https://www.toyota-europe.com/careers"],
    "Honda": ["https://www.honda.ro/cariere"],
    "Hyundai": ["https://www.hyundai.com/worldwide/en/company/careers"],
    "Rimac": ["https://www.rimac-technology.com/careers"],
    "TTTech Auto": ["https://www.tttech-auto.com/career/"],
    "Wind River": ["https://www.windriver.com/company/careers"],
    "GFT": ["https://www.gft.com/int/en/careers", "https://apply.workable.com/gft/"],
    "Reply": ["https://www.reply.com/en/careers", "https://apply.workable.com/reply/"],
    "Publicis Sapient": ["https://careers.publicissapient.com/"],
    "Kraken": ["https://www.kraken.com/careers"],
    "HelloFresh": ["https://careers.hellofresh.com/"],
    "Zalando": ["https://jobs.zalando.com/"],
    "Check24": ["https://jobs.check24.de/"],
    "Adjust": ["https://www.adjust.com/company/careers/"],
    "Flink": ["https://careers.flink.com/"],
}


def canonical_name(name: str) -> str:
    if name in ALIASES:
        return ALIASES[name]
    cleaned = name.strip()
    while True:
        nxt = _ATS_SUFFIX.sub("", cleaned).strip()
        if nxt == cleaned:
            break
        cleaned = nxt
    return ALIASES.get(cleaned, cleaned)


def board_public_url(ats: str, token: str = "", host: str = "", site: str = "") -> str:
    token = (token or "").strip()
    host = (host or "").strip().rstrip("/")
    site = (site or "").strip().strip("/")
    if host.startswith("http://") or host.startswith("https://"):
        return host
    mapping = {
        "greenhouse": f"https://job-boards.greenhouse.io/{token}",
        "lever": f"https://jobs.lever.co/{token}",
        "ashby": f"https://jobs.ashbyhq.com/{token}",
        "smartrecruiters": f"https://careers.smartrecruiters.com/{token}",
        "workable": f"https://apply.workable.com/{token}/",
        "recruitee": f"https://{token}.recruitee.com/",
        "teamtailor": f"https://{token}.teamtailor.com/jobs",
        "personio": f"https://{token}.jobs.personio.com/",
        "breezy": f"https://{token}.breezy.hr/",
        "pinpoint": f"https://{token}.pinpointhq.com/",
        "bamboohr": f"https://{token}.bamboohr.com/careers",
        "google": "https://www.google.com/about/careers/applications/jobs/results/",
        "amazon": "https://www.amazon.jobs/",
        "microsoft": "https://jobs.careers.microsoft.com/",
        "meta": "https://www.metacareers.com/",
        "apple": "https://jobs.apple.com/",
        "comeet": f"https://www.comeet.com/jobs/{token}",
        "successfactors": host or "",
        "careers": host or "",
        "eightfold": f"https://{host}/careers" if host else "",
        "icims": f"https://{host}/jobs/search" if host else "",
        "join": f"https://join.com/companies/{token}",
        "rippling": f"https://ats.rippling.com/{token}/jobs",
        "jazzhr": f"https://{token}.applytojob.com/",
        "freshteam": f"https://{token}.freshteam.com/jobs",
        "softgarden": host or (f"https://{token}.jobs.softgarden.io/" if token else ""),
        "workday": f"https://{host}/{site}" if host and site else (f"https://{host}" if host else ""),
    }
    return mapping.get(ats, "") or ""


def official_urls(name: str) -> list[str]:
    return list(OFFICIAL_CAREERS.get(canonical_name(name), []))


def site_key(site: dict[str, Any]) -> tuple[str, str, str, str]:
    return (
        str(site.get("ats") or ""),
        str(site.get("token") or ""),
        str(site.get("host") or ""),
        str(site.get("site") or ""),
    )
